### PR TITLE
Adding Colab Notebook

### PR DESCRIPTION
**Pull request by sayakpaul**
As discussed in https://github.com/MediaTek-NeuroPilot/mai21-learned-smartphone-isp/issues/1, adding a Colab Notebook to help the community get started more quickly and more easily.

### CODE REVIEW

**Comment by neuropilot-captain** [comment]
Thank you @sayakpaul , this Notebook is a comprehensive and self-contain walk-through for this Challenge. Thank you for the contribution !!!

**Comment by neuropilot-captain** [comment]
@sayakpaul Just to double check if the using of tensorflow v2 is a must for this notebook.
We are think about the compatibility between v1 and v2. If v2 is not MUST, we will suggest to follow the versioning in [prerequisites](https://github.com/MediaTek-NeuroPilot/mai21-learned-smartphone-isp#prerequisites). 

Please feel free to create PR if an update is needed. Thank you

**Comment by sayakpaul** [comment]
@neuropilot-captain TF v2 is only needed for TFLite conversion since the converter that comes with it is way more improved (it's based on MLIR rather than TOCO) than the v1. It allows us to plug and play with different quantization options i.e. FP16, int8, and full int8 which might be non-trivial when using the v1 converter.

**Comment by sayakpaul** [comment]
Also, I would suggest adding a note about the Colab Notebook and correcting the "Open in Colab" link at the top of the notebook. The link should be [this](https://colab.research.google.com/github/MediaTek-NeuroPilot/mai21-learned-smartphone-isp/blob/master/Learned_Smartphone_ISP_Baseline.ipynb).

**Comment by neuropilot-captain** [comment]
@sayakpaul the link is updated. 

For the TFLite conversion, we just confirm that Mediatek's codalab evaluation server support TF2. 
Please feel free to submit the converted model (from this notebook) to [Learned Smartphone ISP Challenge](https://competitions.codalab.org/competitions/28054#learn_the_details) to test the compatibility.

**Comment by sayakpaul** [comment]
Thanks for letting me know. I am currently a bit swamped to run the TFLite model through the server. If I send across the TFLite model here, would you be able to verify it?

**Comment by neuropilot-captain** [comment]
We will suggest to submit model to the evaluation server since the flow is fully automatic. That will create a more transparent test of the model. 

Please post question/problem you encounter in https://competitions.codalab.org/forums/24750/
We will get back to you ASAP.

Thank you.

**Comment by sayakpaul** [comment]
Okay. 

> Please post question/problem you encounter in https://competitions.codalab.org/forums/24750/

But it was suggested to use this forum instead: https://ai-benchmark.net/index.php?threads/learned-smartphone-isp-challenge.4/.

**Comment by neuropilot-captain** [comment]
Our organizer/contributor have activities in both forums.

If the question is related to "Training Data", you will get more responsive feedback in https://ai-benchmark.net/index.php?threads/learned-smartphone-isp-challenge.4/.

if the question is related to "Evaluation",  you will get more responsive feedback in https://competitions.codalab.org/forums/24750/

of-course, you will most responsive feedback [HERE](https://github.com/MediaTek-NeuroPilot/mai21-learned-smartphone-isp/), if it is related to "Training-Pipeline"

**Comment by sayakpaul** [comment]
Okay. Thanks!

**Comment by sayakpaul** [comment]
I tried submitting but it's taking forever. The submission is ~60 MB in size. Is it expected?

**Comment by hsienkaikuo** [comment]
Hi Sayak, 

Would you report the issue (evaluation related) in https://competitions.codalab.org/forums/24750/

And provide the submission ID so that our contributor can look into it. Thank you.

**Comment by sayakpaul** [comment]
Ah sorry. I was able to create a successful submission this time. I submitted a TFLite model that I converted using the latest converter and here are the logs - 

```
adbd is already running as root
/tmp/codalab/tmp3Xa4eT/run/input/res/model.tflite: 1 file pushed, 0 skipped. 67.0 MB/s (6998320 bytes in 0.100s)
STARTING!
Log parameter values verbosely: [0]
Min num runs: [20]
Graph: [/data/local/tmp/MAI_21/model.tflite]
Enable op profiling: [1]
CSV File to export profiling data to: [/data/local/tmp/MAI_21/model/output.csv]
Use neuron : [1]
Neuron allow FP16: [1]
Neuron optimization hint: [1]
Loaded model /data/local/tmp/MAI_21/model.tflite
  adding: log.csv (stored 0%)
/data/local/tmp/MAI_21/model/output.csv: 1 file pulled, 0 skipped. 1.2 MB/s (1968 bytes in 0.002s)
('Avg tflite inference time:', 0.18, ' ms')
```

So, we are good I guess.

**Comment by neuropilot-captain** [comment]
@sayakpaul We are sorry to inform you that there are some technical issues w/ your submission. 

SUBMITTED | SUBMITTED BY | SUBMISSION ID | FILENAME | STATUS | LEADERBOARD | LEARNEDISP-- | -- | -- | -- | -- | -- | --
Feb. 1, 2021, 5:15 p.m. | sayak | 784617 | submission.zip | Finished | True | 8.01-- | -- | -- | -- | -- | -- | --

This issue could be the use of converter later than TF 1.15.0. 
We suggest to use **TF 1.15.0 for TFLite conversion**.

**We also appreciate that if you can submit a PR to update the notebook too**.

**Comment by sayakpaul** [comment]
I am sorry, I didn't get what you meant. From the submission logs, I can see it's running - 

image


If the server isn't capable to support models converted using the TF2 converter then it's missing out on a significant amount of improvements and it might impact a lot of participants. Since TF2 converter supports converting models from TF1 I don't see any issue updating the server to support TFLite models converted using TF2. Not supporting this would restrict the participants to only using TF1 which is absolutely not ideal. I hope you'd agree here.

**Comment by neuropilot-captain** [comment]
There are an Error when running the model on the device. 
At the same time, our evaluation process missed capture these Error.
We hope this does not make bother to you.
However, we have manage to fix the evaluation process.
We will suggest to resubmit the model w/ TF1.15.0 converter.

The TF1.15.0 restriction here is to consider the mobile deployment on the target device.
Any TF version later than 1.15.0 may cause some issue unpredictable.
We hope you understand this.

**Comment by sayakpaul** [comment]
Let's continue the discussion here - https://competitions.codalab.org/forums/24750/5022/. This restriction might lead me to withdraw altogether.

**Pull request merged**
